services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432

  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
    ports:
      - 13306:3306

  mariadb:
    image: mariadb:lts
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_DATABASE: django
    ports:
      - 13307:3306
