# Generated by Django 6.0.2 on 2026-02-06 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0018_rename_succeeded_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dbtaskresult",
            new_name="tasks_db_new_ordering_idx",
            old_name="django_task_new_ordering_idx",
        ),
        migrations.RemoveField(
            model_name="dbtaskresult",
            name="metadata",
        ),
    ]
