# Generated by Django 6.0.2 on 2026-02-06 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_db", "0018_rename_succeeded_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dbtaskresult",
            new_name="tasks_db_new_ordering_idx",
            old_name="django_task_new_ordering_idx",
        ),
        migrations.RenameIndex(
            model_name="dbtaskresult",
            new_name="django_task_queue_n_d08bb4_idx",
            old_name="django_task_queue_n_99c321_idx",
        ),
        migrations.RenameIndex(
            model_name="dbtaskresult",
            new_name="django_task_backend_e5053f_idx",
            old_name="django_task_backend_071754_idx",
        ),
    ]
