# Generated by Django 6.0.2 on 2026-02-06 16:30

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import ProjectState


class RenameIndexIfExists(migrations.RenameIndex):
    """RenameIndex that silently skips if the source index does not exist."""

    def database_forwards(
        self,
        app_label: str,
        schema_editor: BaseDatabaseSchemaEditor,
        from_state: ProjectState,
        to_state: ProjectState,
    ) -> None:
        from_model = from_state.apps.get_model(app_label, self.model_name)
        with schema_editor.connection.cursor() as cursor:
            existing = schema_editor.connection.introspection.get_constraints(
                cursor, from_model._meta.db_table
            )
        if self.old_name not in existing:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(
        self,
        app_label: str,
        schema_editor: BaseDatabaseSchemaEditor,
        from_state: ProjectState,
        to_state: ProjectState,
    ) -> None:
        to_model = to_state.apps.get_model(app_label, self.model_name)
        with schema_editor.connection.cursor() as cursor:
            existing = schema_editor.connection.introspection.get_constraints(
                cursor, to_model._meta.db_table
            )
        if self.new_name not in existing:
            return
        super().database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0018_rename_succeeded_status"),
    ]

    operations = [
        RenameIndexIfExists(
            model_name="dbtaskresult",
            new_name="tasks_db_new_ordering_idx",
            old_name="django_task_new_ordering_idx",
        ),
        migrations.RemoveField(
            model_name="dbtaskresult",
            name="metadata",
        ),
    ]
