# Generated by Django 6.0.2 on 2026-02-06 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_tasks_db",
            "0019_rename_django_task_new_ordering_idx_tasks_db_new_ordering_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbtaskresult",
            name="metadata",
        ),
    ]
