# Generated by Django 6.0.5 on 2026-08-21 13:40

from django.db import migrations, models

import django_tasks_db.models


class Migration(migrations.Migration):
    dependencies = [
        ("django_tasks_database", "0020_update_db_task_result_ordering"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dbtaskresult",
            name="tasks_db_new_ordering_idx",
        ),
        migrations.AddIndex(
            model_name="dbtaskresult",
            index=django_tasks_db.models.ConditionalPartialIndex(
                models.F("status"),
                models.OrderBy(models.F("priority"), descending=True),
                models.OrderBy(models.F("run_after")),
                models.OrderBy(models.F("enqueued_at")),
                condition=models.Q(("status", "READY")),
                name="tasks_db_new_ordering_idx",
            ),
        ),
    ]
